# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d1a7e412a5e5d440dae27f7bec7240ba5d5659d25d7c1ea368cca5375823581ac6bc7617357b28124fe5c24918b81e250b9b84998c9e9f339c8d4b0784932e8

test:
  secret_key_base: 2a0731298d40427770b222abf6228559d9fa052534386621b008936e55084a9e9dedbc3aa41db667ab35c5e350402bd39426e86d98ca0db1274ebc1153296165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
